# Generated by Django 4.1 on 2022-08-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
